#define L_ASSIGN 1
#define L_AT 2
#define L_CBRACE 3
#define L_COMMA 4
#define L_COLON 5
#define L_DAMPER 6
#define L_DCOLON 7
#define L_DEQUALS 8
#define L_DOTDOT 9
#define L_DOTDOTDOT 10
#define L_DSLASH 11
#define L_DVBAR 12
#define L_EOS 13
#define L_EQUALS 14
#define L_GRTR 15
#define L_GRTREQ 16
#define L_LESS 17
#define L_LESSEQ 18
#define L_MINUS 19
#define L_NOT 20
#define L_NOTEQUALS 21
#define L_OBRACE 22
#define L_OBRACK 23
#define L_OPAREN 24
#define L_PLUS 25
#define L_PLUSEQUALS 26
#define L_QUESTION 27
#define L_SLASH 28
#define L_STAR 29
#define L_UNDERSCORE 30
#define L_VBAR 31
#define L_LAST 32
#define K_COMMENT 33
#define K_ID 34
#define K_KEY 35
#define K_NODE 36
#define K_PROCESSING_INSTRUCTION 37
#define K_TEXT 38
#define M_OPERATOR_FIRST 39
#define K_AND 40
#define K_DIV 41
#define K_MOD 42
#define K_OR 43
#define M_OPERATOR_LAST 44
#define M_MULTIPLICATION_TEST_LAST 45
#define L_ASTERISK 46
#define L_CBRACK 47
#define L_CPAREN 48
#define L_DOT 49
#define T_AXIS_NAME 50
#define T_BARE 51
#define T_FUNCTION_NAME 52
#define T_NUMBER 53
#define T_QUOTED 54
#define T_VAR 55
#define M_SEQUENCE 56
#define M_CONCAT 57
#define M_TERNARY 58
#define M_TERNARY_END 59
#define M_ERROR 60
#define M_XPATH 61
#define M_PARSE_FULL 62
#define M_PARSE_SLAX 63
#define M_PARSE_XPATH 64
#define M_PARSE_PARTIAL 65
#define M_JSON 66
#define C_ABSOLUTE 67
#define C_ATTRIBUTE 68
#define C_DESCENDANT 69
#define C_ELEMENT 70
#define C_EXPR 71
#define C_INDEX 72
#define C_NOT 73
#define C_PATH 74
#define C_PREDICATE 75
#define C_TEST 76
#define C_UNION 77
#define C_INT64 78
#define C_UINT64 79
#define C_FLOAT 80
#define C_STRING 81
#define C_BOOLEAN 82
